# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build & Test Java Backend
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      - name: Checkout code
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Set up Corretto 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./backend/gradlew

      - name: Build and test backend
        run: |
          cd backend
          ./gradlew clean build


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo testing complete.
